### PR TITLE
Allow dots and dashes in `text_to_snake_case`

### PR DESCRIPTION
**Pull request by HASPIMA**
Resolves: #98

This PR allows the ids to contain dashes and dots in it.

### CODE REVIEW

**Review by ouhammmourachid — COMMENTED** [review]
It would be great to create test cases that involve strings containing dots (.) and dashes (_) to ensure that the regex modification accurately handles these characters. Can we add some straightforward test cases that cover these scenarios? Thank you! 
https://github.com/ouhammmourachid/mermaid-py/blob/9914ed16e6cd51a8f6eb7a83de44a0a4ba208b6a/mermaid/tests/test_utils.py#L34

**Comment by HASPIMA** [comment]
Will do, that was a foresight on my end, I marked this PR as a draft, I'll mark it ready for review once I add some tests. Thanks your feedback and I'll keep on working on this up until this is ready to merge.

**Comment by HASPIMA** [comment]
Hey @ouhammmourachid, I decided to have the test cases and their respective expected values in a single list. Tell me what you think, whenever a test case is not satisfied, you may see an output like so:
AssertionError: 'other__chars_in_input#' != 'other__chars_in_input_'


These is how it looks like now.
https://github.com/ouhammmourachid/mermaid-py/blob/1c9ed349ff72e047a4523d8744ecb38d4970efa0/mermaid/tests/test_utils.py#L35-L47

Let me know what you think and if we should add more test cases or do something else. I'm all ears.

**Review by ouhammmourachid — APPROVED** [review]
I believe everything is in order. The bug fix will be included in the upcoming release, `v0.2.5`. Thank you sincerely for your valuable contribution!

**Comment by HASPIMA** [comment]
Thanks to you too, I'm glad I was of help to you and this project. Hope to contribute once again the future. I'll be looking forward to it, and getting the new version. Have a good one!

**Pull request merged**
